kind: PersistentVolume
apiVersion: v1
metadata:
  name: config-volume-pv1
  namespace: observability
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/koushik.malga/open-telemetry/opentelemetry"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: config-volume-pvc1
  namespace: observability
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
